config/routes.rb
Rails.application.routes.draw do
  # List Routing
  get 'lists/new'
  post 'lists', to: 'lists#create'
  
  
  # Item Routing
  get 'items/add'
  post 'items', to: 'items#create'
  get 'items/show_single_record'
  get 'items/update'
  get 'items/show_all_records'
  delete '/', to: 'items#destroy'
  delete '/items/show_all_records', to: 'items#destroy'
  patch 'items', to: 'items#patch'

  get 'items/delete_all', to: 'items#delete_all'
  
 
  
  root to:'items#home'
  
  
  #resources :items

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :list
   validates_presence_of :title, :work_time
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
   after_filter :flash_to_headers

  private

    def flash_to_headers
      return unless request.xhr?
      msg = flash_message
      #replace german umlaute encoded in utf-8 to html escaped ones
      msg = msg.gsub("ä","&auml;").gsub("ü","&uuml;").gsub("ö","&ouml;").gsub("Ä","&Auml;").gsub("Ü","&Uuml;").gsub("Ö","&Ouml;").gsub("ß","&szlig;")
      response.headers['X-Message'] = msg
      response.headers["X-Message-Type"] = flash_type.to_s

      #flash.discard # don't want the flash to appear when you reload page
    end

    def flash_message
      [:error, :warning, :notice].each do |type|
        return flash[type] unless flash[type].blank?
      end
      # if we don't return something here, the above code will return "error, warning, notice"
      return ''
    end

    def flash_type
      #:keep will instruct the js to not update or remove the shown message.
      #just write flash[:keep] = true (or any other value) in your controller code
      [:error, :warning, :notice, :keep].each do |type|
        return type unless flash[type].blank?
      end
      #don't return the array from above which would happen if we don't have an explicit return statement
      #returning :empty will also allow you to easily know that no flash message was transmitted
      return :empty
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
   
    helper_method :sort_column, :sort_direction
    respond_to :html, :js
     
  
  def add
      @item  = Item.new
     
     
  end
 
  def create
      
      @item = Item.new(secure_params)
	if @item.save
        s = "submitted"
        
      
      
      if flash[:isUpdate]
          s = "updated"
         @var = Item.find(flash[:toDestroy]).destroy
         
         
      end
       #flash[:notice] = "Task #{@item.title} is #{s}"
      
            respond_to do |format|
                show_all_records(@item.list_id, true)
               format.js {render "show_all_records"}
                
                
            end
    
    else

        render action: 'add'
      
        
        
	end
    

  end
  
  def show_single_record
      @item = Item.find(params[:id])
  end
  
  def destroy
       @item = Item.find(params[:id]).destroy
     #  flash[:warning] = "Task #{@item.title} is deleted"
     
       respond_to do |format|
         show_all_records(@item.list_id,true)
         format.js { render "show_all_records"} 
         
       end
      
  end


  def delete_all
    Item.all.destroy_all
    redirect_to root_path
  end
  
  def update
	  @var  = Item.new
      @item = Item.find(params[:id])
      flash[:isUpdate] = true
      flash[:toDestroy] = @item.id
      
      
  end
  
  def home
      
      @list = List.new
      @lists = List.all
  end
  
  def show_all_records(listID=0, flag = false)
    if(flag)
        @items = Item.where(list_id: listID).order(sort_column+ " " + sort_direction)
      else
       @items = Item.where(list_id: params[:id]).order(sort_column+ " " + sort_direction)
     end
       
  end
  
  def sort
    # id here is the list_id
      @items = Item.find(params[:id])
      
  end
  
  private 
  def secure_params
      params.require(:item).permit(:title,:due_date,:work_time,:completed,:list_id)
  end
  
  def sort_column
    Item.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end
  
  def create
    @list = List.new(secure_params)
    if @list.save
     # flash[:notice] = "List #{@list.name} is created"
      redirect_to root_path
    end
  end
  
  private
  def secure_params
      params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    

def sortable(column, title = nil)
  title ||= column.titleize
  column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}#, {:class => css_class}
end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_add.html.erb
<div class ="modal-dialog modal-content modal-body" id="general-form">
<%= simple_form_for @item, remote: true do |form|%>
<%= render 'error_messages' %>
<%= form.input :title, class: 'form-control'%>
<%= form.input :due_date%>
<%= form.input :work_time %>
<%= form.input :completed %>
<%= form.hidden_field :list_id, value: params[:list_id] %>
<%= form.button :submit,'Submit', class: 'submit', id: "add-item"%>
<%= link_to 'Cancel', items_show_all_records_path(id: params[:list_id]),id: 'add-item', class: 'btn btn-default', remote: true %>
<% end %>
</div>

app/views/items/_error_messages.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    
    <% @item.errors.full_messages.each do |msg| %>
    
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_show_single_record.html.erb
<!-- <div calss="modal fade">-->
<div class="modal-dialog modal-content modal-body" id="general-form">
<%= simple_format(@item.title) %>
<%= @item.due_date %>
<% wor = simple_format(@item.work_time.to_s << ' hrs') %>
<%= wor %>
<% isCompleted = @item.completed %>
<% if (isCompleted == true) %>
<%= simple_format("The task is completed") %>
<% else %>
<%= simple_format("The task is not completed") %>
<% end %>
<%= link_to  items_update_path(:id=>@item.id), remote: true, class: 'btn btn-success' do%>
<i class="glyphicon glyphicon-pencil"></i> Update
<% end %>
<%= " " %>
<%= link_to items_show_all_records_path(:id=>@item.id, :list_id=>params[:list_id]),id: "delete-item", remote: true, method: :delete,  class: 'btn btn-danger' do %>
<i class="glyphicon glyphicon-minus"></i> Delete
<% end %>
</div>

app/views/items/_update.html.erb
<div class ="modal-dialog modal-content modal-body" id="general-form">
<%= simple_form_for @var, remote: true do |form|%>
<%= render 'error_messages' %>
<%= form.input :title, input_html: {value: @item.title}%>
<%= form.input :due_date%>
<%= form.input :work_time, input_html: {value: @item.work_time} %>
<%= form.input :completed, input_html: {:checked => @item.completed}%>
<%= form.hidden_field :list_id, value: @item.list_id %>
<%= form.button :submit, 'Submit', class: 'submit', id: "update-item" %>
<%= link_to 'Cancel', items_show_all_records_path(:id=>@item.list_id) , id: "update-item", class: 'btn btn-default', remote: true %>
<% end %>
</div>

app/views/items/add.html.erb
<div class ="form">
<%= simple_form_for @item do |form|%>
<%= form.input :title%>
<%= form.input :creation_date %>
<%= form.input :expiration_date%>
<%= form.input :work_time %>
<%= form.input :completed %>
<%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>
</div>

app/views/items/add.js.erb
$("#items-modal").html("<%= j render 'add' %>")
$("#items-modal").modal("add")

app/views/items/delete.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/delete_all.js.erb
var delete_all_confirm, r, txt;

$(document).ajaxComplete(function(event, request) {

#delete_all_confirm = function() {};

r = confirm('Press a button!');

if (r === true) {
  <% puts "yeeeees" %>

} 
else {
  txt = 'You pressed Cancel!';
}
                                                  });

app/views/items/home.html.erb
	  <!-- home.html.erb -->
	 <div id="home-items"></div>
<div id="items-modal"></div>

app/views/items/show_all_records.js.erb
$("#home-items").html("<%= j render 'show_all_records'%>")
$(document).on("click","#add-item, #delete-item, #update-item",function(){
                            $("#general-form").css("display", "none");
                            });

app/views/items/show_single_record.html.erb
<div class="container">
<%= simple_format(@item.title) %>
<%= @item.creation_date %>
</br>
<%= @item.expiration_date %>
<%= simple_format(@item.work_time.to_s) %>
<% isCompleted = @item.completed %>
<% if (isCompleted == true) %>
<%= simple_format("The task is completed") %>
<% else %>
<%= simple_format("The work is not completed") %>
<% end %>
<%= link_to  items_update_path(:id=>@item.id), class: 'btn btn-success' do%>
<i class="glyphicon glyphicon-pencil"></i> Update
<% end %>
<%= link_to root_path(:id=>@item.id), method: :delete,  class: 'btn btn-danger' do %>
<i class="glyphicon glyphicon-minus"></i> Delete
<% end %>
</div>

app/views/items/show_single_record.js.erb
$("#items-modal").html("<%= j render 'show_single_record' %>")
$("#items-modal").modal("show_single_record")

app/views/items/update.html.erb
<div class ="form">
<%= simple_form_for @var do |form|%>
<!-- <%= form.input :id, input_html: {value: @item.id} %>-->
<%= form.input :title, input_html: {value: @item.title}%>
<%= form.input :creation_date, input_html: {value: @item.expiration_date} %>
<%= form.input :expiration_date%>
<%= form.input :work_time, input_html: {value: @item.work_time} %>
<%= form.input :completed, input_html: {:checked => @item.completed}%>
<%= form.button :submit, 'Submit', class: 'submit' %>
<% end %>
</div>

app/views/items/update.js.erb
$("#items-modal").html("<%= j render 'update' %>")
$("#items-modal").modal("add")

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse sidebar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
        <!-- This is for the button with three bars when the window minimized -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Smart List</a>
    </div>
    
    
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
		
      <ul class="nav navbar-nav">
      <%= render 'layouts/navigation_links' %>
      </ul>
    
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<%# lists %>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Lists<span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-list-alt"></span></a>
<% @lists.each do |list| %>
    <ul class="dropdown-menu forAnimate" role="menu">
    
        <li>
            <%= link_to simple_format(list.name), 				items_show_all_records_path(:id=>list.id), remote: true, id:  "add-item"%>
        </li>
    </ul>
	<% end %>
</li>


<%# items %>


<li><% link_to 'Add',items_add_path, remote: true %> </li>


<%# add new list %>
<li>
	<%= link_to lists_new_path, remote: true do%>
		<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-plus-sign"></span> Add List
	<% end %>
	<div id="new-list"></div>
</li>


<%# delete all items %>
<li>
    <%= link_to items_delete_all_path, data: {confirm: "Are you sure ?"} do %>
        <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-trash"></span>
        Delete All Tasks
    <% end %>
</li>
<li><% link_to 'Update', items_update_path, remote: true %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Smart List" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Smart List" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
 	
    <%= render 'layouts/navigation' %>
		
  	  <main class="main">
       <!-- <%= render 'layouts/messages' %> -->
       <div id="flash_hook"></div>
       <%= yield %>
      </main>
	  	   <!-- <%= render 'layouts/navigation/footer' %> -->

    </body>
</html>

app/views/layouts/navigation/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    Anything you want
  </div>
  <strong>
    Copyright © 2016
    <a href="#"> Company</a>
  </strong>
  All rights reserved.
</footer>

app/views/layouts/navigation/_header.html.erb
<header class="main-header">
  <a class="logo" href="/">
Smart List
</a>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope-o">
            </i><span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 4 messages
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#"> </a>
                  <div class="pull-left">
                    <img class="img-circle" alt="User Image" src="http://placehold.it/160x160"> </img>
                  </div>
                  <h4>
                    Sender Name
                    <small>
                    <i class="fa fa-clock-o">
                    </i>5 mins
                    </small>
                  </h4>
                  <p>
                    Message Excerpt
                  </p>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> See All Messages</a>
            </li>
          </ul>
        </li>
        <li class="dropdown notifications-menu">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell-o">
            </i><span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 10 notifications
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                <i class="ion ion-ios-people info">
                </i>Notification title
                </a>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> View all</a>
            </li>
          </ul>
        </li>
        <li class="dropdown tasks-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-flag-o">
            </i><span class="label label-danger">9</span>
            </a>
          <ul class="dropdown-menu">
            <li class="header">
              You have 9 tasks
            </li>
            <li>
              <ul class="menu">
                <li>
                  <a href="#">
                  </a> 
                  <h3>
                    Design some buttons
                  <small class="pull-right">20%</small>
                  </h3>
                  <div class="progress xs">
                    <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" class="progress-bar progress-bar-aqua" role="progressbar" style="width: 20%">
<span class="sr-only">20% Complete</span>
</div>
                  </div>
                </li>
              </ul>
            </li>
            <li class="footer">
              <a href="#"> View all tasks</a>
            </li>
          </ul>
        </li>
        <li class="dropdown user user-menu">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
          <span class="hidden-xs">Alexander Pierce</span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <img class="img-circle" alt="User Image" src="http://placehold.it/160x160"> </img>
              <p>
                Alexander Pierce - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#"> Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"> Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#"> Friends</a>
              </div>
            </li>
            <li class="user-footer">
              <div class="pull-left">
                <a class="btn btn-default btn-flat" href="#"> Profile</a>
              </div>
              <div class="pull-right">
                <a class="btn btn-default btn-flat" href="#"> Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/navigation/_layout.html.erb
<%= render "layouts/navigation"%>

app/views/layouts/navigation/_sidebar.html.erb
<div class="main-sidebar">
  <div class="sidebar">
    <div class="user-panel">
      <div class="pull-left image">
        <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
      </div>
      <div class="pull-left info">
        <p>
          User Name
        </p>
        <a href="#">
          <i class="fa fa-circle text-success">
          </i>Online
          </a>
      </div>
    </div>
	<!-- Add a new list button -->
	
	
	<%= form_for @list, url: {:controller=>'lists', action: "create"}, html: {class: "sidebar-form"} do |f| %>
	  <%= f.text_field :name, placeholder: "New list ...", label: false, input_html: { class: 'form-control'} %>
	  <%= f.submit "Create" %>
	<% end %>
	
	
   
	
	<div id="new-list" class="input-group">
	</div>
	
   
      
      
    
    <ul class="sidebar-menu">
      <li class="header">
        Lists
      </li>
      <% @lists.each do |list| %>
          <li>
            <%= link_to simple_format(list.name), items_show_all_records_path(:id=>list.id), remote: true %>
          </li>  
      <% end %>
      
      <li>
        <a href="#">
        <span>Another Link</span>
        </a>
      </li>
      <li class="treeview">
        <a href="#">
          <span>Multilevel</span>
          <i class="fa fa-angle-left pull-right">
          </i></a>
        <ul class="treeview-menu">
          <li>
            <a href="#"> Link in level 2</a>
          </li>
          <li>
            <a href="#"> Link in level 2</a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/lists/_new.html.erb
<div>
<%= simple_form_for @list, remote: true do |form|%>
<%= form.input :name, label: false, placeholder: 'new list ...' %>
<% end %>
</div>

app/views/lists/new.js.erb
$("#new-list").html("<%= j render 'new' %>")